version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./public:/usr/src/app/public
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"